// <auto-generated />
using BudgetPlanner.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetPlanner.Api.Migrations
{
    [DbContext(typeof(BudgetPlannerDbContext))]
    [Migration("20240925083401_ThirdMigration")]
    partial class ThirdMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetPlanner.Api.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlanned")
                        .HasColumnType("bit");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 4.55f,
                            CategoryId = 1,
                            IsPlanned = true,
                            Month = "January",
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            Amount = 4.55f,
                            CategoryId = 2,
                            IsPlanned = true,
                            Month = "February",
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            Amount = 61.5f,
                            CategoryId = 1,
                            IsPlanned = false,
                            Month = "March",
                            Year = 2024
                        },
                        new
                        {
                            Id = 4,
                            Amount = 6f,
                            CategoryId = 2,
                            IsPlanned = true,
                            Month = "April",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("BudgetPlanner.Api.Entities.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Храна"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Превоз"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Сметки"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Останато"
                        });
                });

            modelBuilder.Entity("BudgetPlanner.Api.Entities.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlanned")
                        .HasColumnType("bit");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Incomes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 4.55f,
                            CategoryId = 1,
                            IsPlanned = true,
                            Month = "January",
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            Amount = 4.55f,
                            CategoryId = 2,
                            IsPlanned = true,
                            Month = "February",
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            Amount = 61.5f,
                            CategoryId = 1,
                            IsPlanned = false,
                            Month = "March",
                            Year = 2024
                        },
                        new
                        {
                            Id = 4,
                            Amount = 6f,
                            CategoryId = 3,
                            IsPlanned = true,
                            Month = "April",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("BudgetPlanner.Api.Entities.IncomeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IncomeCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Плата"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Патни Трошоци"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Останато"
                        });
                });

            modelBuilder.Entity("BudgetPlanner.Api.Entities.Expense", b =>
                {
                    b.HasOne("BudgetPlanner.Api.Entities.ExpenseCategory", "ExpenseCategory")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");
                });

            modelBuilder.Entity("BudgetPlanner.Api.Entities.Income", b =>
                {
                    b.HasOne("BudgetPlanner.Api.Entities.IncomeCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
